### PR TITLE
chore: upgrade LibreOffice to version 7.4.0

### LINKED ISSUE #8: LibreOffice 7.4 version image
With the version 7.4 of LibreOffice one can specify filters for pdf export.

See https://vmiklos.hu/blog/pdf-convert-to.html for details.

### PR DESCRIPTION
**Pull request by bjalt**
fixes #8

### CODE REVIEW

**Comment by vladgolubev** [comment]
Wow, great!

Could you please also update this line? So the docker image has a proper tag

https://github.com/shelfio/libreoffice-lambda-base-image/blob/master/.circleci/config.yml#L45

**Comment by bjalt** [comment]
@vladgolubev What about https://github.com/shelfio/libreoffice-lambda-base-image/blob/master/.circleci/config.yml#L15?

**Comment by vladgolubev** [comment]
@bjalt yeap, there as well! Good catch. Probably could be refactored to reuse variables, like

```
parameters:
  lo_version: xxx


<< pipeline.lo_version >>
```

**Comment by bjalt** [comment]
@vladgolubev I haven't worked with circleCI yet. Looking through the [documentation](https://circleci.com/docs/pipeline-variables#pipeline-parameters-in-configuration) it should probably be like:

```yaml
parameters:
  lo_version: xxx

# ....
tag: << pipeline.parameters.lo_version >>
```

Can you confirm?

**Comment by vladgolubev** [comment]
@bjalt correct

**Comment by bjalt** [comment]
@vladgolubev Changed as requested.

**Review by vladgolubev — APPROVED** [review]

**Pull request merged**
